# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 272f643bc80dca67286dd1f52f58ad80f0cb339164f2e04af6fb71bfd665ae89547babc12adb560ee31cb40f60e4c1b75998fa03b97ddc10bf46e9c8059ce640

test:
  secret_key_base: 68719cb650b5d7f63aaf0ee5f95d3f8db6d5cf0630fe7ba8f52e260d00e4ef550929cfa4e6f5fc5b257fdbfef02827a12c5614a8b1d29449c093df975977b341

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
